version: "3"
services:
  nginx: # 服务名称，用户自定义
    image: nginx:latest  # 镜像版本
    ports:
      - 80:80  # 暴露端口
    volumes: # 挂载
      - /root/music_ol/nginx/html:/usr/share/nginx/html
      - /root/music_ol/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment: # 指定用户root的密码
      - MYSQL_ROOT_PASSWORD=admin
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    volumes:
      - /root/music_ol/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  musicol:
    image: musicol:latest
    build: . # 表示以当前目录下的Dockerfile开始构建镜像
    ports:
      - 8481:8481
    volumes: # 挂载
      - /root/music_ol/songs:/root/music_ol/songs
      - /root/music_ol/img:/root/music_ol/img
    depends_on: # 依赖与mysql、redis，其实可以不填，默认已经表示可以
      - mysql
      - redis
      - rabbitmq